version: '3.8'

services:
  sentidos_db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: sentidos_cobrancas
      POSTGRES_USER: sentidos_user
      POSTGRES_PASSWORD: sentidos_password
    volumes:
      - sentidos_db_data:/var/lib/postgresql/data
    networks:
      - traefik_network

  sentidos_cobrancas:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://sentidos_user:sentidos_password@sentidos_db:5432/sentidos_cobrancas
    volumes:
      # Mantemos o volume do database.json para permitir a migração automática inicial dos dados
      - ./database.json:/app/database.json
    networks:
      - traefik_network
    depends_on:
      - sentidos_db
    labels:
      - "traefik.enable=true"
      # Roteamento do domínio da aplicação para o container
      - "traefik.http.routers.sentidos.rule=Host(`siscobra.isentidos.net.br`)"
      - "traefik.http.routers.sentidos.entrypoints=websecure"
      - "traefik.http.routers.sentidos.tls.certresolver=letsencrypt"
      - "traefik.http.services.sentidos.loadbalancer.server.port=3001"
      - "traefik.http.services.sentidos.loadbalancer.passHostHeader=true"

volumes:
  sentidos_db_data:

networks:
  traefik_network:
    external: true
